// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oewhgzsqstcybeqbuyhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ld2hnenNxc3RjeWJlcWJ1eWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTUyMzUsImV4cCI6MjA2NzczMTIzNX0.pcKHYCZ3ulC9dvfYyKVtY4Snrb0jG_-8JmEenqQVu9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});